[workspace]
members = [
    # Data
    "data/re-wz",
    "data/game_data",
    "data/re-wz-ui",

    # client
    "client/shroom_launchar",

    # server
    "server/shrooming",
    "server/proto95",
    "server/login",
    "server/game",
    "server/mono",
    "server/data",
    "server/data/migration",
]
exclude = ["client/shroom_hook","client/shroom_ffi"]

# Shroom crates for now
[patch.crates-io]
shroom_net = { path = "/home/jonas/Dokumente/projects/open-rust-ms/net/crates/shroom_net" }
shroom_net_derive = { path = "/home/jonas/Dokumente/projects/open-rust-ms/net/crates/shroom_net_derive" }
