[workspace]
resolver = "2"
members = [
    # Data
    # "data/re-wz",
    "data/game_data",

    # client
    "client/shroom_launchar",

    # server
    "server/shrooming",
    "server/proto95",
    "server/login",
    "server/game",
    "server/mono",
    "server/data",
    "server/data/migration",
]
exclude = ["client/shroom_hook","client/shroom_ffi"]

# Shroom crates for now
[patch.crates-io]
shroom-net = { git = "https://github.com/OpenRustMS/net.git", branch = "jz/tick_feature" }
shroom-pkt = { git = "https://github.com/OpenRustMS/net.git", branch = "jz/tick_feature" }
