[workspace]
members = [
    # Data
    "data/re-wz",
    "data/game_data",

    # client
    "client/moople_launchar",

    # server
    "server/shrooming",
    "server/proto95",
    "server/login",
    "server/game",
    "server/mono",
    "server/data",
    "server/data/migration",
]
exclude = ["client/moople_hook","client/moople_ffi"]

# Shroom crates for now
[patch.crates-io]
shroom_net = { git = "https://github.com/OpenRustMS/net" }
shroom_net_derive = { git = "https://github.com/OpenRustMS/net" }